var sourcesIndex = {};
sourcesIndex["wayland_backend"] = {"name":"","dirs":[{"name":"rs","dirs":[{"name":"client_impl","files":["mod.rs"]},{"name":"server_impl","files":["client.rs","common_poll.rs","handle.rs","mod.rs","registry.rs"]}],"files":["client_api.rs","debug.rs","map.rs","mod.rs","server_api.rs","socket.rs","wire.rs"]},{"name":"sys","dirs":[{"name":"client_impl","files":["mod.rs"]},{"name":"server_impl","files":["mod.rs"]}],"files":["client_api.rs","mod.rs","server_api.rs"]},{"name":"types","files":["client.rs","mod.rs","server.rs"]}],"files":["core_interfaces.rs","lib.rs","protocol.rs"]};
sourcesIndex["wayland_client"] = {"name":"","files":["conn.rs","event_queue.rs","lib.rs"]};
sourcesIndex["wayland_cursor"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_egl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["wayland_protocols"] = {"name":"","files":["ext.rs","lib.rs","protocol_macro.rs","wp.rs","xdg.rs"]};
sourcesIndex["wayland_protocols_misc"] = {"name":"","files":["lib.rs","protocol_macro.rs"]};
sourcesIndex["wayland_protocols_plasma"] = {"name":"","files":["lib.rs","protocol_macro.rs"]};
sourcesIndex["wayland_protocols_wlr"] = {"name":"","files":["lib.rs","protocol_macro.rs"]};
sourcesIndex["wayland_scanner"] = {"name":"","files":["c_interfaces.rs","client_gen.rs","common.rs","interfaces.rs","lib.rs","parse.rs","protocol.rs","server_gen.rs","util.rs"]};
sourcesIndex["wayland_server"] = {"name":"","files":["client.rs","dispatch.rs","display.rs","global.rs","lib.rs","socket.rs"]};
sourcesIndex["wayland_sys"] = {"name":"","files":["client.rs","common.rs","cursor.rs","egl.rs","lib.rs","server.rs"]};
sourcesIndex["wayland_tests"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
